name: Biweekly Release

on:
  # Run on the 1st and 15th of every month (approx. every 2 weeks)
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          # Ensure the token is not persisted to avoid credential issues when pushing changes.
          persist-credentials: false
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install && uv venv

      - name: Install GitPython
        run: uv pip install gitpython

      - name: Run biweekly_release.py
        run: uv run biweekly_release.py

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add pyproject.toml
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(ver): Bump version")
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  create-release:
    needs: update-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Create release
        uses: seriaati/create-release@main
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
          python_version: "3.9"
          tool: "uv"