name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Build and publish
        run: |
          uv build -p 3.9
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
